/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "white": "#FFFFFF",
        "soft-sage": "#BDDDFC",
        "sage-hover": "#88BDF2",
        "text-main": "#384959",
        "on-secondary": "#ffffff",
        "surface-tint": "#6A89A7",
        "secondary": "#88BDF2",
        "inverse-primary": "#BDDDFC",
        "inverse-surface": "#384959",
        "surface-container": "#D7ECFD",
        "background": "#F6FAFE",
        "primary-container": "#88BDF2",
        "primary": "#6A89A7",
        "surface-bright": "#F6FAFE",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#384959",
        "on-tertiary-fixed-variant": "#7d2d00",
        "tertiary-fixed-dim": "#ffb596",
        "on-primary-container": "#384959",
        "secondary-container": "#BDDDFC",
        "on-surface": "#384959",
        "surface-variant": "#BDDDFC",
        "on-error-container": "#93000a",
        "on-surface-variant": "#6A89A7",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-tertiary-container": "#ffede6",
        "tertiary-container": "#bc4800",
        "surface": "#F6FAFE",
        "outline-variant": "#BDDDFC",
        "primary-fixed": "#BDDDFC",
        "tertiary": "#943700",
        "tertiary-fixed": "#ffdbcd",
        "on-secondary-fixed": "#384959",
        "on-primary": "#FFFFFF",
        "surface-dim": "#BDDDFC",
        "primary-fixed-dim": "#88BDF2",
        "surface-container-high": "#BDDDFC",
        "on-tertiary-fixed": "#360f00",
        "outline": "#6A89A7",
        "on-background": "#384959",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#BDDDFC",
        "on-secondary-fixed-variant": "#384959",
        "inverse-on-surface": "#F6FAFE",
        "surface-container-low": "#EEF7FF",
        "surface-container-highest": "#88BDF2",
        "secondary-fixed-dim": "#BDDDFC",
        "error": "#ba1a1a",
        "on-primary-fixed": "#384959",
        "on-primary-fixed-variant": "#384959"
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px"
      }
    },
  },
  plugins: [],
}
